- hosts: k8s_controlplane
  become: true
  vars:
    cert_manager_version: "v1.19.4"

  tasks:
    - name: Ensure kubeconfig
      include_tasks: ../../tasks/k8s_ensure_kubeconfig.yaml

    - name: Ensure helm
      include_tasks: ../../tasks/k8s_ensure_helm.yaml

    - name: Add jetsack Helm repo
      command: helm repo add jetstack https://charts.jetstack.io
      register: repo_add
      failed_when: repo_add.rc != 0 and ("already exists" not in (repo_add.stderr | lower))
      changed_when: repo_add.rc == 0

    - name: Helm repo update
      command: helm repo update
      changed_when: false
    
    - name: Install/Upgrade cert-manager
      command: >
        helm upgrade --install cert-manager jetstack/cert-manager
        --namespace cert-manager
        --create-namespace
        --version {{ cert_manager_version }}
        --set installCRDs=true
      environment:
        KUBECONFIG: "{{ k8s_kubeconfig }}"