[k8s_controlplane]
frodo-ringbearer ansible_host=192.168.0.44 ansible_user=ubuntu
[k8s_workers]
merry ansible_host=192.168.0.243 ansible_user=ubuntu
gimli ansible_host=192.168.0.141 ansible_user=ubuntu
[k8s_observability]
smeagol ansible_host=192.168.0.37 ansible_user=ubuntu

[k8s:children]
k8s_controlplane
k8s_workers
k8s_observability
